### PR TITLE
Fall back to anonymous if not authorized

### PR DESCRIPTION
**Pull request by viktordick**

### CODE REVIEW

**Comment by viktordick** [comment]
On a typical PerFact system, there is a `UserFolder` in `/` and a `SimpleUserFolder` in `/PerFact`. It seems that for a long time, the `SimpleUserFolder` yielded `None` if the authorization was not successful, but this has recently changed: If the user was found, but the password was wrong or the user locked, the `getUserAuthorizadion` script now returns `False`, indicating that the authorization was unsuccessful and should not be tried in the level above.

However, due to the `raise Redirect('/')`, this resulted in an endless redirect if someone tried to authenticate with Basic Authentication: The load balancer redirects a call to `/` to a path with full acquisition context, which again redirects to `/`.

Raising `Unauthorized` seems to be the better choice here. Note that this whole part is only relevant for Basic Authentication and we usually do not allow Basic Authentication from outside of the system, but there are exceptions, usually from other systems accessing some endpoint. These should obtain a clean `Unauthorized` and not an endless redirect.

**Comment by viktordick** [comment]
A note regarding the other changes here:

- The backwards compatibility call to `getUserDetails` even in the case where the user is not authenticated can now be removed since `ZPerFactMods` takes care of initializing the session with every call unless explicitly turned off.
- The changed import is due to the following warning that I always see when running the `zodbsync` tests:
```
  /home/viktor/git/zodbsync/.tox/py3/lib/python3.10/site-packages/Products/SimpleUserFolder/SimpleUserFolder.py:10: DeprecationWarning: BasicUserFolder is deprecated. The standard Zope user folder implementation has moved to OFS.userfolder.  Please depend on Zope and import from  OFS.userfolder or use the new minimal  user folder classes from AccessControl.userfolder. This backward compatibility shim will be removed in AccessControl version 6.
    from AccessControl.User import BasicUserFolder
```
I checked that the Python 2 version also allows this changed import, but have not yet checked that it yields the same result there.
- The whitespace change is due to flake8

**Comment by Wiseqube** [comment]
Just checked, even for 2.13 AccessControl.User is just a wrapper for AccessControl.users

**Review by jan-jockusch — APPROVED** [review]
A welcome cleanup. I trust this is being evaluated thoroughly at the Froneri installation. LGTM

**Comment by viktordick** [comment]
@jan-jockusch No, it has not been tested on that system specifically. I just tested on `ema-devel-2020`.

Instead of the endless redirect I now get a redirect to `user_login`, which then returns a page with `403: Forbidden` status code.

**Comment by viktordick** [comment]
To explain: we obtain an Unauthorized, but our error handling within Zope changes this into a redirect to the login page, which returns a `403` to make sure that a) AJAX and API calls do not assume that this is a valid result and b) the browser does not show the basic authentication dialog (which we usually do not want in a context below `/PerFact`).

**Comment by viktordick** [comment]
I think this needs to change again.
Currently, this yields an oracle function if someone may use BasicAuth. I get a different result whether I use an existing user with a wrong password or a nonexisting user with a wrong password.
Not sure yet if this should be fixed here or within Zope.

**Comment by viktordick** [comment]
@jan-jockusch I changed the behavior to void the oracle function. The behavior is now:

- If authentication was successful and `getUserAuthorization` returns a username, use that user
- If we are at top-level *or* `getUserAuthorization` returned `False`, try to authenticate the anonymous user and use that if successful
- Else, return `None`, which allows a higher `acl_users` to try authentication.

This version is currently active on `ema-devel-2020` and I have no oracle function anymore and no endless redirect. Using the application as a top-level `Manager` user also works again (was broken for a short time).

**Review by jan-jockusch — APPROVED** [review]
LGTM! Makes sense.

**Pull request merged**
